tasks:
  - name: Library
    init: yarn install
    command: yarn watch
    
  - name: Web App 
    init: cd example && yarn install 
    command: cd example && yarn start

ports:
  - name: Web App
    port: 3000
    visibility: private
    onOpen: notify