tasks:
  - name: Package
    init: yarn install
    command: yarn watch

  - name: Web App
    init: cd example && yarn install
    command: cd example && yarn build

  - name: Install usefull packages
    init: |
      npm i -g serve

ports:
  - name: Web App
    port: 3000
    visibility: private
    onOpen: notify