name: Deploy

on:
  release:
    types: [created]

jobs:
  publish-npm:
    name: Deploying package to npm 😱
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Building Package 🌨️
        run: |
          yarn install
          yarn build:lib

      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  building-example:
    needs: publish-npm
    name: Building Example (Web App) ⚒️
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Installing Packages 📝
        run: yarn install

      - name: Building App 📦
        run: yarn build:web

      - name: Uploading web_build artifact ☁️
        uses: actions/upload-artifact@v2
        with:
          name: web_build
          path: build/web
          retention-days: 1

      - name: Deploy to vercel
        run: |
          # Build .vercel configuration
          mkdir build/web/.vercel
          touch build/web/.vercel/project.json
          echo '{ "orgId": "${{ secrets.VERCEL_ORG_ID }}", "projectId": "${{ secrets.VERCEL_PROJECT_ID }}" }' > build/web/.vercel/project.json

          # Deploy to vercel
          vercel deploy build/web -t ${{ secrets.VERCEL_TOKEN }} --prod -y